// <auto-generated />
using CRUD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUD.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240114175338_SeedUsers")]
    partial class SeedUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRUD.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            FirstName = "Emily",
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            FirstName = "Daniel",
                            LastName = "Rodriguez"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            FirstName = "Olivia",
                            LastName = "Mitchell"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 5,
                            FirstName = "Sophia",
                            LastName = "Taylor"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 4,
                            FirstName = "Ethan",
                            LastName = "Martinez"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
